# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  build:
    name: "devinggo"
    arch: "amd64"
    system: "linux"
    mod: "none"
    packSrc: "resource,manifest"                    # 将resource目录打包进可执行文件，静态资源无需单独部署
    packDst: "internal/packed/packed.go"   # 打包后生成的Go文件路径，一般使用相对路径指定到本项目目录中
    path: "./bin"
    extra: " -ldflags \"-s -w\" "
    version: v1.0.0
    cgo: 0
  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - ccr.ccs.tencentyun.com/devinghub
  gen:
    dao:
      - tablesEx: "system_migrations"
        link: "mysql:devinggo:mysql_zbCA5h@tcp(db-mysql-8adauv:3306)/devinggo?loc=Local&parseTime=true&charset=utf8mb4&multiStatements=true"
        jsonCase: "CamelLower"
        descriptionTag:  true
        noModelComment:  false
        gJsonSupport: true
        overwriteDao: true
        clear: true