// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// settingCrontabDao is the data access object for the table setting_crontab.
// You can define custom methods on it to extend its functionality as needed.
type settingCrontabDao struct {
	*internal.SettingCrontabDao
}

var (
	// SettingCrontab is a globally accessible object for table setting_crontab operations.
	SettingCrontab = settingCrontabDao{internal.NewSettingCrontabDao()}
)

// Add your custom methods and functionality below.
