// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// internalSettingCrontabLogDao is internal type for wrapping internal DAO implements.
type internalSettingCrontabLogDao = *internal.SettingCrontabLogDao

// settingCrontabLogDao is the data access object for table setting_crontab_log.
// You can define custom methods on it to extend its functionality as you wish.
type settingCrontabLogDao struct {
	internalSettingCrontabLogDao
}

var (
	// SettingCrontabLog is globally public accessible object for table setting_crontab_log operations.
	SettingCrontabLog = settingCrontabLogDao{
		internal.NewSettingCrontabLogDao(),
	}
)

// Fill with you ideas below.
