// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// settingGenerateColumnsDao is the data access object for the table setting_generate_columns.
// You can define custom methods on it to extend its functionality as needed.
type settingGenerateColumnsDao struct {
	*internal.SettingGenerateColumnsDao
}

var (
	// SettingGenerateColumns is a globally accessible object for table setting_generate_columns operations.
	SettingGenerateColumns = settingGenerateColumnsDao{internal.NewSettingGenerateColumnsDao()}
)

// Add your custom methods and functionality below.
