// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// settingConfigGroupDao is the data access object for the table setting_config_group.
// You can define custom methods on it to extend its functionality as needed.
type settingConfigGroupDao struct {
	*internal.SettingConfigGroupDao
}

var (
	// SettingConfigGroup is a globally accessible object for table setting_config_group operations.
	SettingConfigGroup = settingConfigGroupDao{internal.NewSettingConfigGroupDao()}
)

// Add your custom methods and functionality below.
