// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// internalSettingConfigDao is internal type for wrapping internal DAO implements.
type internalSettingConfigDao = *internal.SettingConfigDao

// settingConfigDao is the data access object for table setting_config.
// You can define custom methods on it to extend its functionality as you wish.
type settingConfigDao struct {
	internalSettingConfigDao
}

var (
	// SettingConfig is globally public accessible object for table setting_config operations.
	SettingConfig = settingConfigDao{
		internal.NewSettingConfigDao(),
	}
)

// Fill with you ideas below.
