// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// internalSettingGenerateTablesDao is internal type for wrapping internal DAO implements.
type internalSettingGenerateTablesDao = *internal.SettingGenerateTablesDao

// settingGenerateTablesDao is the data access object for table setting_generate_tables.
// You can define custom methods on it to extend its functionality as you wish.
type settingGenerateTablesDao struct {
	internalSettingGenerateTablesDao
}

var (
	// SettingGenerateTables is globally public accessible object for table setting_generate_tables operations.
	SettingGenerateTables = settingGenerateTablesDao{
		internal.NewSettingGenerateTablesDao(),
	}
)

// Fill with you ideas below.
