// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// settingGenerateTablesDao is the data access object for the table setting_generate_tables.
// You can define custom methods on it to extend its functionality as needed.
type settingGenerateTablesDao struct {
	*internal.SettingGenerateTablesDao
}

var (
	// SettingGenerateTables is a globally accessible object for table setting_generate_tables operations.
	SettingGenerateTables = settingGenerateTablesDao{internal.NewSettingGenerateTablesDao()}
)

// Add your custom methods and functionality below.
