// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// internalSettingConfigGroupDao is internal type for wrapping internal DAO implements.
type internalSettingConfigGroupDao = *internal.SettingConfigGroupDao

// settingConfigGroupDao is the data access object for table setting_config_group.
// You can define custom methods on it to extend its functionality as you wish.
type settingConfigGroupDao struct {
	internalSettingConfigGroupDao
}

var (
	// SettingConfigGroup is globally public accessible object for table setting_config_group operations.
	SettingConfigGroup = settingConfigGroupDao{
		internal.NewSettingConfigGroupDao(),
	}
)

// Fill with you ideas below.
