// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// settingCrontabLogDao is the data access object for the table setting_crontab_log.
// You can define custom methods on it to extend its functionality as needed.
type settingCrontabLogDao struct {
	*internal.SettingCrontabLogDao
}

var (
	// SettingCrontabLog is a globally accessible object for table setting_crontab_log operations.
	SettingCrontabLog = settingCrontabLogDao{internal.NewSettingCrontabLogDao()}
)

// Add your custom methods and functionality below.
