// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// settingConfigDao is the data access object for the table setting_config.
// You can define custom methods on it to extend its functionality as needed.
type settingConfigDao struct {
	*internal.SettingConfigDao
}

var (
	// SettingConfig is a globally accessible object for table setting_config operations.
	SettingConfig = settingConfigDao{internal.NewSettingConfigDao()}
)

// Add your custom methods and functionality below.
