// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// internalSystemQueueMessageDao is internal type for wrapping internal DAO implements.
type internalSystemQueueMessageDao = *internal.SystemQueueMessageDao

// systemQueueMessageDao is the data access object for table system_queue_message.
// You can define custom methods on it to extend its functionality as you wish.
type systemQueueMessageDao struct {
	internalSystemQueueMessageDao
}

var (
	// SystemQueueMessage is globally public accessible object for table system_queue_message operations.
	SystemQueueMessage = systemQueueMessageDao{
		internal.NewSystemQueueMessageDao(),
	}
)

// Fill with you ideas below.
