// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// internalSystemApiDao is internal type for wrapping internal DAO implements.
type internalSystemApiDao = *internal.SystemApiDao

// systemApiDao is the data access object for table system_api.
// You can define custom methods on it to extend its functionality as you wish.
type systemApiDao struct {
	internalSystemApiDao
}

var (
	// SystemApi is globally public accessible object for table system_api operations.
	SystemApi = systemApiDao{
		internal.NewSystemApiDao(),
	}
)

// Fill with you ideas below.
