// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// internalSystemDeptLeaderDao is internal type for wrapping internal DAO implements.
type internalSystemDeptLeaderDao = *internal.SystemDeptLeaderDao

// systemDeptLeaderDao is the data access object for table system_dept_leader.
// You can define custom methods on it to extend its functionality as you wish.
type systemDeptLeaderDao struct {
	internalSystemDeptLeaderDao
}

var (
	// SystemDeptLeader is globally public accessible object for table system_dept_leader operations.
	SystemDeptLeader = systemDeptLeaderDao{
		internal.NewSystemDeptLeaderDao(),
	}
)

// Fill with you ideas below.
