// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// internalSystemQueueMessageReceiveDao is internal type for wrapping internal DAO implements.
type internalSystemQueueMessageReceiveDao = *internal.SystemQueueMessageReceiveDao

// systemQueueMessageReceiveDao is the data access object for table system_queue_message_receive.
// You can define custom methods on it to extend its functionality as you wish.
type systemQueueMessageReceiveDao struct {
	internalSystemQueueMessageReceiveDao
}

var (
	// SystemQueueMessageReceive is globally public accessible object for table system_queue_message_receive operations.
	SystemQueueMessageReceive = systemQueueMessageReceiveDao{
		internal.NewSystemQueueMessageReceiveDao(),
	}
)

// Fill with you ideas below.
