// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// internalSystemUploadfileDao is internal type for wrapping internal DAO implements.
type internalSystemUploadfileDao = *internal.SystemUploadfileDao

// systemUploadfileDao is the data access object for table system_uploadfile.
// You can define custom methods on it to extend its functionality as you wish.
type systemUploadfileDao struct {
	internalSystemUploadfileDao
}

var (
	// SystemUploadfile is globally public accessible object for table system_uploadfile operations.
	SystemUploadfile = systemUploadfileDao{
		internal.NewSystemUploadfileDao(),
	}
)

// Fill with you ideas below.
