// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// internalSystemAppApiDao is internal type for wrapping internal DAO implements.
type internalSystemAppApiDao = *internal.SystemAppApiDao

// systemAppApiDao is the data access object for table system_app_api.
// You can define custom methods on it to extend its functionality as you wish.
type systemAppApiDao struct {
	internalSystemAppApiDao
}

var (
	// SystemAppApi is globally public accessible object for table system_app_api operations.
	SystemAppApi = systemAppApiDao{
		internal.NewSystemAppApiDao(),
	}
)

// Fill with you ideas below.
