// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// systemDictDataDao is the data access object for the table system_dict_data.
// You can define custom methods on it to extend its functionality as needed.
type systemDictDataDao struct {
	*internal.SystemDictDataDao
}

var (
	// SystemDictData is a globally accessible object for table system_dict_data operations.
	SystemDictData = systemDictDataDao{internal.NewSystemDictDataDao()}
)

// Add your custom methods and functionality below.
