// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// systemApiDao is the data access object for the table system_api.
// You can define custom methods on it to extend its functionality as needed.
type systemApiDao struct {
	*internal.SystemApiDao
}

var (
	// SystemApi is a globally accessible object for table system_api operations.
	SystemApi = systemApiDao{internal.NewSystemApiDao()}
)

// Add your custom methods and functionality below.
