// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// systemQueueMessageReceiveDao is the data access object for the table system_queue_message_receive.
// You can define custom methods on it to extend its functionality as needed.
type systemQueueMessageReceiveDao struct {
	*internal.SystemQueueMessageReceiveDao
}

var (
	// SystemQueueMessageReceive is a globally accessible object for table system_queue_message_receive operations.
	SystemQueueMessageReceive = systemQueueMessageReceiveDao{internal.NewSystemQueueMessageReceiveDao()}
)

// Add your custom methods and functionality below.
