// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// internalSystemApiGroupDao is internal type for wrapping internal DAO implements.
type internalSystemApiGroupDao = *internal.SystemApiGroupDao

// systemApiGroupDao is the data access object for table system_api_group.
// You can define custom methods on it to extend its functionality as you wish.
type systemApiGroupDao struct {
	internalSystemApiGroupDao
}

var (
	// SystemApiGroup is globally public accessible object for table system_api_group operations.
	SystemApiGroup = systemApiGroupDao{
		internal.NewSystemApiGroupDao(),
	}
)

// Fill with you ideas below.
