// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// systemModulesDao is the data access object for the table system_modules.
// You can define custom methods on it to extend its functionality as needed.
type systemModulesDao struct {
	*internal.SystemModulesDao
}

var (
	// SystemModules is a globally accessible object for table system_modules operations.
	SystemModules = systemModulesDao{internal.NewSystemModulesDao()}
)

// Add your custom methods and functionality below.
