// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// systemPostDao is the data access object for the table system_post.
// You can define custom methods on it to extend its functionality as needed.
type systemPostDao struct {
	*internal.SystemPostDao
}

var (
	// SystemPost is a globally accessible object for table system_post operations.
	SystemPost = systemPostDao{internal.NewSystemPostDao()}
)

// Add your custom methods and functionality below.
