// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// systemNoticeDao is the data access object for the table system_notice.
// You can define custom methods on it to extend its functionality as needed.
type systemNoticeDao struct {
	*internal.SystemNoticeDao
}

var (
	// SystemNotice is a globally accessible object for table system_notice operations.
	SystemNotice = systemNoticeDao{internal.NewSystemNoticeDao()}
)

// Add your custom methods and functionality below.
