// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// systemAppDao is the data access object for the table system_app.
// You can define custom methods on it to extend its functionality as needed.
type systemAppDao struct {
	*internal.SystemAppDao
}

var (
	// SystemApp is a globally accessible object for table system_app operations.
	SystemApp = systemAppDao{internal.NewSystemAppDao()}
)

// Add your custom methods and functionality below.
