// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// internalSystemOperLogDao is internal type for wrapping internal DAO implements.
type internalSystemOperLogDao = *internal.SystemOperLogDao

// systemOperLogDao is the data access object for table system_oper_log.
// You can define custom methods on it to extend its functionality as you wish.
type systemOperLogDao struct {
	internalSystemOperLogDao
}

var (
	// SystemOperLog is globally public accessible object for table system_oper_log operations.
	SystemOperLog = systemOperLogDao{
		internal.NewSystemOperLogDao(),
	}
)

// Fill with you ideas below.
