// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// systemDeptLeaderDao is the data access object for the table system_dept_leader.
// You can define custom methods on it to extend its functionality as needed.
type systemDeptLeaderDao struct {
	*internal.SystemDeptLeaderDao
}

var (
	// SystemDeptLeader is a globally accessible object for table system_dept_leader operations.
	SystemDeptLeader = systemDeptLeaderDao{internal.NewSystemDeptLeaderDao()}
)

// Add your custom methods and functionality below.
