// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// systemOperLogDao is the data access object for the table system_oper_log.
// You can define custom methods on it to extend its functionality as needed.
type systemOperLogDao struct {
	*internal.SystemOperLogDao
}

var (
	// SystemOperLog is a globally accessible object for table system_oper_log operations.
	SystemOperLog = systemOperLogDao{internal.NewSystemOperLogDao()}
)

// Add your custom methods and functionality below.
