// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// internalSystemApiLogDao is internal type for wrapping internal DAO implements.
type internalSystemApiLogDao = *internal.SystemApiLogDao

// systemApiLogDao is the data access object for table system_api_log.
// You can define custom methods on it to extend its functionality as you wish.
type systemApiLogDao struct {
	internalSystemApiLogDao
}

var (
	// SystemApiLog is globally public accessible object for table system_api_log operations.
	SystemApiLog = systemApiLogDao{
		internal.NewSystemApiLogDao(),
	}
)

// Fill with you ideas below.
