// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// systemUserDao is the data access object for the table system_user.
// You can define custom methods on it to extend its functionality as needed.
type systemUserDao struct {
	*internal.SystemUserDao
}

var (
	// SystemUser is a globally accessible object for table system_user operations.
	SystemUser = systemUserDao{internal.NewSystemUserDao()}
)

// Add your custom methods and functionality below.
