// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// systemUserDeptDao is the data access object for the table system_user_dept.
// You can define custom methods on it to extend its functionality as needed.
type systemUserDeptDao struct {
	*internal.SystemUserDeptDao
}

var (
	// SystemUserDept is a globally accessible object for table system_user_dept operations.
	SystemUserDept = systemUserDeptDao{internal.NewSystemUserDeptDao()}
)

// Add your custom methods and functionality below.
