// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// systemApiGroupDao is the data access object for the table system_api_group.
// You can define custom methods on it to extend its functionality as needed.
type systemApiGroupDao struct {
	*internal.SystemApiGroupDao
}

var (
	// SystemApiGroup is a globally accessible object for table system_api_group operations.
	SystemApiGroup = systemApiGroupDao{internal.NewSystemApiGroupDao()}
)

// Add your custom methods and functionality below.
