// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// systemLoginLogDao is the data access object for the table system_login_log.
// You can define custom methods on it to extend its functionality as needed.
type systemLoginLogDao struct {
	*internal.SystemLoginLogDao
}

var (
	// SystemLoginLog is a globally accessible object for table system_login_log operations.
	SystemLoginLog = systemLoginLogDao{internal.NewSystemLoginLogDao()}
)

// Add your custom methods and functionality below.
