// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// internalSystemUserPostDao is internal type for wrapping internal DAO implements.
type internalSystemUserPostDao = *internal.SystemUserPostDao

// systemUserPostDao is the data access object for table system_user_post.
// You can define custom methods on it to extend its functionality as you wish.
type systemUserPostDao struct {
	internalSystemUserPostDao
}

var (
	// SystemUserPost is globally public accessible object for table system_user_post operations.
	SystemUserPost = systemUserPostDao{
		internal.NewSystemUserPostDao(),
	}
)

// Fill with you ideas below.
