// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// systemRoleMenuDao is the data access object for the table system_role_menu.
// You can define custom methods on it to extend its functionality as needed.
type systemRoleMenuDao struct {
	*internal.SystemRoleMenuDao
}

var (
	// SystemRoleMenu is a globally accessible object for table system_role_menu operations.
	SystemRoleMenu = systemRoleMenuDao{internal.NewSystemRoleMenuDao()}
)

// Add your custom methods and functionality below.
