// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// internalSystemRoleMenuDao is internal type for wrapping internal DAO implements.
type internalSystemRoleMenuDao = *internal.SystemRoleMenuDao

// systemRoleMenuDao is the data access object for table system_role_menu.
// You can define custom methods on it to extend its functionality as you wish.
type systemRoleMenuDao struct {
	internalSystemRoleMenuDao
}

var (
	// SystemRoleMenu is globally public accessible object for table system_role_menu operations.
	SystemRoleMenu = systemRoleMenuDao{
		internal.NewSystemRoleMenuDao(),
	}
)

// Fill with you ideas below.
