// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// internalSystemDictTypeDao is internal type for wrapping internal DAO implements.
type internalSystemDictTypeDao = *internal.SystemDictTypeDao

// systemDictTypeDao is the data access object for table system_dict_type.
// You can define custom methods on it to extend its functionality as you wish.
type systemDictTypeDao struct {
	internalSystemDictTypeDao
}

var (
	// SystemDictType is globally public accessible object for table system_dict_type operations.
	SystemDictType = systemDictTypeDao{
		internal.NewSystemDictTypeDao(),
	}
)

// Fill with you ideas below.
