// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// systemUploadfileDao is the data access object for the table system_uploadfile.
// You can define custom methods on it to extend its functionality as needed.
type systemUploadfileDao struct {
	*internal.SystemUploadfileDao
}

var (
	// SystemUploadfile is a globally accessible object for table system_uploadfile operations.
	SystemUploadfile = systemUploadfileDao{internal.NewSystemUploadfileDao()}
)

// Add your custom methods and functionality below.
