// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// systemRoleDeptDao is the data access object for the table system_role_dept.
// You can define custom methods on it to extend its functionality as needed.
type systemRoleDeptDao struct {
	*internal.SystemRoleDeptDao
}

var (
	// SystemRoleDept is a globally accessible object for table system_role_dept operations.
	SystemRoleDept = systemRoleDeptDao{internal.NewSystemRoleDeptDao()}
)

// Add your custom methods and functionality below.
