// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// systemUserRoleDao is the data access object for the table system_user_role.
// You can define custom methods on it to extend its functionality as needed.
type systemUserRoleDao struct {
	*internal.SystemUserRoleDao
}

var (
	// SystemUserRole is a globally accessible object for table system_user_role operations.
	SystemUserRole = systemUserRoleDao{internal.NewSystemUserRoleDao()}
)

// Add your custom methods and functionality below.
