// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// systemQueueMessageDao is the data access object for the table system_queue_message.
// You can define custom methods on it to extend its functionality as needed.
type systemQueueMessageDao struct {
	*internal.SystemQueueMessageDao
}

var (
	// SystemQueueMessage is a globally accessible object for table system_queue_message operations.
	SystemQueueMessage = systemQueueMessageDao{internal.NewSystemQueueMessageDao()}
)

// Add your custom methods and functionality below.
