// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// systemDictTypeDao is the data access object for the table system_dict_type.
// You can define custom methods on it to extend its functionality as needed.
type systemDictTypeDao struct {
	*internal.SystemDictTypeDao
}

var (
	// SystemDictType is a globally accessible object for table system_dict_type operations.
	SystemDictType = systemDictTypeDao{internal.NewSystemDictTypeDao()}
)

// Add your custom methods and functionality below.
