// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// internalSystemNoticeDao is internal type for wrapping internal DAO implements.
type internalSystemNoticeDao = *internal.SystemNoticeDao

// systemNoticeDao is the data access object for table system_notice.
// You can define custom methods on it to extend its functionality as you wish.
type systemNoticeDao struct {
	internalSystemNoticeDao
}

var (
	// SystemNotice is globally public accessible object for table system_notice operations.
	SystemNotice = systemNoticeDao{
		internal.NewSystemNoticeDao(),
	}
)

// Fill with you ideas below.
