// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// systemDeptDao is the data access object for the table system_dept.
// You can define custom methods on it to extend its functionality as needed.
type systemDeptDao struct {
	*internal.SystemDeptDao
}

var (
	// SystemDept is a globally accessible object for table system_dept operations.
	SystemDept = systemDeptDao{internal.NewSystemDeptDao()}
)

// Add your custom methods and functionality below.
