// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// systemUserPostDao is the data access object for the table system_user_post.
// You can define custom methods on it to extend its functionality as needed.
type systemUserPostDao struct {
	*internal.SystemUserPostDao
}

var (
	// SystemUserPost is a globally accessible object for table system_user_post operations.
	SystemUserPost = systemUserPostDao{internal.NewSystemUserPostDao()}
)

// Add your custom methods and functionality below.
