// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// internalSystemLoginLogDao is internal type for wrapping internal DAO implements.
type internalSystemLoginLogDao = *internal.SystemLoginLogDao

// systemLoginLogDao is the data access object for table system_login_log.
// You can define custom methods on it to extend its functionality as you wish.
type systemLoginLogDao struct {
	internalSystemLoginLogDao
}

var (
	// SystemLoginLog is globally public accessible object for table system_login_log operations.
	SystemLoginLog = systemLoginLogDao{
		internal.NewSystemLoginLogDao(),
	}
)

// Fill with you ideas below.
