// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// internalSystemAppGroupDao is internal type for wrapping internal DAO implements.
type internalSystemAppGroupDao = *internal.SystemAppGroupDao

// systemAppGroupDao is the data access object for table system_app_group.
// You can define custom methods on it to extend its functionality as you wish.
type systemAppGroupDao struct {
	internalSystemAppGroupDao
}

var (
	// SystemAppGroup is globally public accessible object for table system_app_group operations.
	SystemAppGroup = systemAppGroupDao{
		internal.NewSystemAppGroupDao(),
	}
)

// Fill with you ideas below.
