// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// systemAppGroupDao is the data access object for the table system_app_group.
// You can define custom methods on it to extend its functionality as needed.
type systemAppGroupDao struct {
	*internal.SystemAppGroupDao
}

var (
	// SystemAppGroup is a globally accessible object for table system_app_group operations.
	SystemAppGroup = systemAppGroupDao{internal.NewSystemAppGroupDao()}
)

// Add your custom methods and functionality below.
