// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// internalSystemModulesDao is internal type for wrapping internal DAO implements.
type internalSystemModulesDao = *internal.SystemModulesDao

// systemModulesDao is the data access object for table system_modules.
// You can define custom methods on it to extend its functionality as you wish.
type systemModulesDao struct {
	internalSystemModulesDao
}

var (
	// SystemModules is globally public accessible object for table system_modules operations.
	SystemModules = systemModulesDao{
		internal.NewSystemModulesDao(),
	}
)

// Fill with you ideas below.
