// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// systemApiLogDao is the data access object for the table system_api_log.
// You can define custom methods on it to extend its functionality as needed.
type systemApiLogDao struct {
	*internal.SystemApiLogDao
}

var (
	// SystemApiLog is a globally accessible object for table system_api_log operations.
	SystemApiLog = systemApiLogDao{internal.NewSystemApiLogDao()}
)

// Add your custom methods and functionality below.
