// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// internalSystemUserRoleDao is internal type for wrapping internal DAO implements.
type internalSystemUserRoleDao = *internal.SystemUserRoleDao

// systemUserRoleDao is the data access object for table system_user_role.
// You can define custom methods on it to extend its functionality as you wish.
type systemUserRoleDao struct {
	internalSystemUserRoleDao
}

var (
	// SystemUserRole is globally public accessible object for table system_user_role operations.
	SystemUserRole = systemUserRoleDao{
		internal.NewSystemUserRoleDao(),
	}
)

// Fill with you ideas below.
