// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// systemRoleDao is the data access object for the table system_role.
// You can define custom methods on it to extend its functionality as needed.
type systemRoleDao struct {
	*internal.SystemRoleDao
}

var (
	// SystemRole is a globally accessible object for table system_role operations.
	SystemRole = systemRoleDao{internal.NewSystemRoleDao()}
)

// Add your custom methods and functionality below.
