// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// systemAppApiDao is the data access object for the table system_app_api.
// You can define custom methods on it to extend its functionality as needed.
type systemAppApiDao struct {
	*internal.SystemAppApiDao
}

var (
	// SystemAppApi is a globally accessible object for table system_app_api operations.
	SystemAppApi = systemAppApiDao{internal.NewSystemAppApiDao()}
)

// Add your custom methods and functionality below.
