// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// internalSystemUserDao is internal type for wrapping internal DAO implements.
type internalSystemUserDao = *internal.SystemUserDao

// systemUserDao is the data access object for table system_user.
// You can define custom methods on it to extend its functionality as you wish.
type systemUserDao struct {
	internalSystemUserDao
}

var (
	// SystemUser is globally public accessible object for table system_user operations.
	SystemUser = systemUserDao{
		internal.NewSystemUserDao(),
	}
)

// Fill with you ideas below.
